##端口配置
#server:
#  port: 8033

## Dubbo 服务提供者配置
# provider应用名称
dubbo:
  application:
    name: dubbo-registry-zookeeper-provider-demo2

# Dubbo组件扫描的基础包
#dubbo:
  scan:
    base-packages: com.flaya.dubbo.service
# Dubbo应用程序名称，的默认值是$ {spring.application.name}
## dubbo.application.name=${spring.application.name}
# Dubbo 协议与端口
  protocol:
    name: dubbo
    port: -1

## Dubbo 注册地址 N/A表示直连方式
#dubbo.registry.address=N/A
  registry:
    address: zookeeper://192.168.251.221:2181?backup=192.168.251.124:2181,192.168.251.122:2181,192.168.251.11:2181

embedded:
  zookeeper:
    port: 2181
#embedded.zookeeper.port = 2181
#dubbo.registry.address=zookeeper://127.0.0.1:${embedded.zookeeper.port}

demo:
  service:
    version: 1.0.0